### ISSUE TITLE
[Bug Report] Notification Issue

### ISSUE THREAD

**Issue by bakinazik** [jamal2362/URL-Radio#33] opened 2023-03-05 12:22 UTC
When I play a station and switch to another station, the picture of the previous station is stuck in the notification.

**Comment by bakinazik** [comment] 2023-03-05 15:54
https://user-images.githubusercontent.com/64368231/222971180-127a3c8a-3ad4-4fe5-85ac-064694f9fd6e.mp4

**Comment by jamal2362** [comment] 2023-03-05 18:55
Hey 🙂

I cannot reproduce this.
I'll leave this issue open in case I get it too.
I have tested it from Android 5 to Android 13 and do not have this issue.

**Comment by bakinazik** [comment] 2023-03-09 07:44
Android 12, MIUI 13.0.3, Poco F2 Pro

**Comment by jamal2362** [comment] 2023-03-14 10:47
Does the problem still exist ?

Don't have the Issue on me so far. 
After a few days of testing...

Have you tried to disabled battery optimization for the app ?

**Comment by bakinazik** [comment] 2023-03-14 11:30
transistor app have this issue too.
and yeah i tried the give all permission but still same issue.

**Comment by jamal2362** [comment] 2023-03-18 11:32
I'm closing here.
Please check your OS for issues.

**Closed as completed by jamal2362** 2023-03-18 11:32 UTC
Labels: Cannot be reproduced
